// Code generated by protoc-gen-go. DO NOT EDIT.
// source: perspective.proto

package perspectivego

import (
	fmt "fmt"
	joygo "github.com/AletheiaWareLLC/joygo"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type World struct {
	Name                 string                   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size                 uint32                   `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	BackgroundColour     string                   `protobuf:"bytes,3,opt,name=background_colour,json=backgroundColour,proto3" json:"background_colour,omitempty"`
	ForegroundColour     string                   `protobuf:"bytes,4,opt,name=foreground_colour,json=foregroundColour,proto3" json:"foreground_colour,omitempty"`
	Puzzle               []*Puzzle                `protobuf:"bytes,5,rep,name=puzzle,proto3" json:"puzzle,omitempty"`
	Shader               map[string]*joygo.Shader `protobuf:"bytes,6,rep,name=shader,proto3" json:"shader,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *World) Reset()         { *m = World{} }
func (m *World) String() string { return proto.CompactTextString(m) }
func (*World) ProtoMessage()    {}
func (*World) Descriptor() ([]byte, []int) {
	return fileDescriptor_530ac3ae2cb4c87b, []int{0}
}

func (m *World) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_World.Unmarshal(m, b)
}
func (m *World) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_World.Marshal(b, m, deterministic)
}
func (m *World) XXX_Merge(src proto.Message) {
	xxx_messageInfo_World.Merge(m, src)
}
func (m *World) XXX_Size() int {
	return xxx_messageInfo_World.Size(m)
}
func (m *World) XXX_DiscardUnknown() {
	xxx_messageInfo_World.DiscardUnknown(m)
}

var xxx_messageInfo_World proto.InternalMessageInfo

func (m *World) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *World) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *World) GetBackgroundColour() string {
	if m != nil {
		return m.BackgroundColour
	}
	return ""
}

func (m *World) GetForegroundColour() string {
	if m != nil {
		return m.ForegroundColour
	}
	return ""
}

func (m *World) GetPuzzle() []*Puzzle {
	if m != nil {
		return m.Puzzle
	}
	return nil
}

func (m *World) GetShader() map[string]*joygo.Shader {
	if m != nil {
		return m.Shader
	}
	return nil
}

type Location struct {
	W                    int32    `protobuf:"varint,1,opt,name=w,proto3" json:"w,omitempty"`
	X                    int32    `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	Z                    int32    `protobuf:"varint,4,opt,name=z,proto3" json:"z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_530ac3ae2cb4c87b, []int{1}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetW() int32 {
	if m != nil {
		return m.W
	}
	return 0
}

func (m *Location) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Location) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Location) GetZ() int32 {
	if m != nil {
		return m.Z
	}
	return 0
}

type Outline struct {
	Mesh                 string   `protobuf:"bytes,1,opt,name=mesh,proto3" json:"mesh,omitempty"`
	Colour               string   `protobuf:"bytes,2,opt,name=colour,proto3" json:"colour,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Outline) Reset()         { *m = Outline{} }
func (m *Outline) String() string { return proto.CompactTextString(m) }
func (*Outline) ProtoMessage()    {}
func (*Outline) Descriptor() ([]byte, []int) {
	return fileDescriptor_530ac3ae2cb4c87b, []int{2}
}

func (m *Outline) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Outline.Unmarshal(m, b)
}
func (m *Outline) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Outline.Marshal(b, m, deterministic)
}
func (m *Outline) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Outline.Merge(m, src)
}
func (m *Outline) XXX_Size() int {
	return xxx_messageInfo_Outline.Size(m)
}
func (m *Outline) XXX_DiscardUnknown() {
	xxx_messageInfo_Outline.DiscardUnknown(m)
}

var xxx_messageInfo_Outline proto.InternalMessageInfo

func (m *Outline) GetMesh() string {
	if m != nil {
		return m.Mesh
	}
	return ""
}

func (m *Outline) GetColour() string {
	if m != nil {
		return m.Colour
	}
	return ""
}

type Block struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mesh                 string    `protobuf:"bytes,2,opt,name=mesh,proto3" json:"mesh,omitempty"`
	Colour               string    `protobuf:"bytes,3,opt,name=colour,proto3" json:"colour,omitempty"`
	Location             *Location `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_530ac3ae2cb4c87b, []int{3}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Block) GetMesh() string {
	if m != nil {
		return m.Mesh
	}
	return ""
}

func (m *Block) GetColour() string {
	if m != nil {
		return m.Colour
	}
	return ""
}

func (m *Block) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

type Goal struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mesh                 string    `protobuf:"bytes,2,opt,name=mesh,proto3" json:"mesh,omitempty"`
	Colour               string    `protobuf:"bytes,3,opt,name=colour,proto3" json:"colour,omitempty"`
	Location             *Location `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Goal) Reset()         { *m = Goal{} }
func (m *Goal) String() string { return proto.CompactTextString(m) }
func (*Goal) ProtoMessage()    {}
func (*Goal) Descriptor() ([]byte, []int) {
	return fileDescriptor_530ac3ae2cb4c87b, []int{4}
}

func (m *Goal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Goal.Unmarshal(m, b)
}
func (m *Goal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Goal.Marshal(b, m, deterministic)
}
func (m *Goal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Goal.Merge(m, src)
}
func (m *Goal) XXX_Size() int {
	return xxx_messageInfo_Goal.Size(m)
}
func (m *Goal) XXX_DiscardUnknown() {
	xxx_messageInfo_Goal.DiscardUnknown(m)
}

var xxx_messageInfo_Goal proto.InternalMessageInfo

func (m *Goal) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Goal) GetMesh() string {
	if m != nil {
		return m.Mesh
	}
	return ""
}

func (m *Goal) GetColour() string {
	if m != nil {
		return m.Colour
	}
	return ""
}

func (m *Goal) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

type Portal struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mesh                 string    `protobuf:"bytes,2,opt,name=mesh,proto3" json:"mesh,omitempty"`
	Colour               string    `protobuf:"bytes,3,opt,name=colour,proto3" json:"colour,omitempty"`
	Location             *Location `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Link                 *Location `protobuf:"bytes,5,opt,name=link,proto3" json:"link,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Portal) Reset()         { *m = Portal{} }
func (m *Portal) String() string { return proto.CompactTextString(m) }
func (*Portal) ProtoMessage()    {}
func (*Portal) Descriptor() ([]byte, []int) {
	return fileDescriptor_530ac3ae2cb4c87b, []int{5}
}

func (m *Portal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Portal.Unmarshal(m, b)
}
func (m *Portal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Portal.Marshal(b, m, deterministic)
}
func (m *Portal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Portal.Merge(m, src)
}
func (m *Portal) XXX_Size() int {
	return xxx_messageInfo_Portal.Size(m)
}
func (m *Portal) XXX_DiscardUnknown() {
	xxx_messageInfo_Portal.DiscardUnknown(m)
}

var xxx_messageInfo_Portal proto.InternalMessageInfo

func (m *Portal) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Portal) GetMesh() string {
	if m != nil {
		return m.Mesh
	}
	return ""
}

func (m *Portal) GetColour() string {
	if m != nil {
		return m.Colour
	}
	return ""
}

func (m *Portal) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Portal) GetLink() *Location {
	if m != nil {
		return m.Link
	}
	return nil
}

type Sphere struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mesh                 string    `protobuf:"bytes,2,opt,name=mesh,proto3" json:"mesh,omitempty"`
	Colour               string    `protobuf:"bytes,3,opt,name=colour,proto3" json:"colour,omitempty"`
	Location             *Location `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Sphere) Reset()         { *m = Sphere{} }
func (m *Sphere) String() string { return proto.CompactTextString(m) }
func (*Sphere) ProtoMessage()    {}
func (*Sphere) Descriptor() ([]byte, []int) {
	return fileDescriptor_530ac3ae2cb4c87b, []int{6}
}

func (m *Sphere) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sphere.Unmarshal(m, b)
}
func (m *Sphere) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sphere.Marshal(b, m, deterministic)
}
func (m *Sphere) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sphere.Merge(m, src)
}
func (m *Sphere) XXX_Size() int {
	return xxx_messageInfo_Sphere.Size(m)
}
func (m *Sphere) XXX_DiscardUnknown() {
	xxx_messageInfo_Sphere.DiscardUnknown(m)
}

var xxx_messageInfo_Sphere proto.InternalMessageInfo

func (m *Sphere) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Sphere) GetMesh() string {
	if m != nil {
		return m.Mesh
	}
	return ""
}

func (m *Sphere) GetColour() string {
	if m != nil {
		return m.Colour
	}
	return ""
}

func (m *Sphere) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

type Puzzle struct {
	Outline *Outline  `protobuf:"bytes,1,opt,name=outline,proto3" json:"outline,omitempty"`
	Block   []*Block  `protobuf:"bytes,3,rep,name=block,proto3" json:"block,omitempty"`
	Goal    []*Goal   `protobuf:"bytes,4,rep,name=goal,proto3" json:"goal,omitempty"`
	Portal  []*Portal `protobuf:"bytes,5,rep,name=portal,proto3" json:"portal,omitempty"`
	Sphere  []*Sphere `protobuf:"bytes,6,rep,name=sphere,proto3" json:"sphere,omitempty"`
	// Tutorial: Tap to Drop, Swipe to Rotate, Use the Block
	// Other: puzzle number
	Description string `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	// Lower score (ie fewer rotations) are better
	// hit target: 5 stars
	// target + 1: 4 stars
	// target + 2: 3 stars
	// target + 3: 2 stars
	// target + 4: 1 star
	// else: no stars
	Target               uint32   `protobuf:"varint,8,opt,name=target,proto3" json:"target,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Puzzle) Reset()         { *m = Puzzle{} }
func (m *Puzzle) String() string { return proto.CompactTextString(m) }
func (*Puzzle) ProtoMessage()    {}
func (*Puzzle) Descriptor() ([]byte, []int) {
	return fileDescriptor_530ac3ae2cb4c87b, []int{7}
}

func (m *Puzzle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Puzzle.Unmarshal(m, b)
}
func (m *Puzzle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Puzzle.Marshal(b, m, deterministic)
}
func (m *Puzzle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Puzzle.Merge(m, src)
}
func (m *Puzzle) XXX_Size() int {
	return xxx_messageInfo_Puzzle.Size(m)
}
func (m *Puzzle) XXX_DiscardUnknown() {
	xxx_messageInfo_Puzzle.DiscardUnknown(m)
}

var xxx_messageInfo_Puzzle proto.InternalMessageInfo

func (m *Puzzle) GetOutline() *Outline {
	if m != nil {
		return m.Outline
	}
	return nil
}

func (m *Puzzle) GetBlock() []*Block {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *Puzzle) GetGoal() []*Goal {
	if m != nil {
		return m.Goal
	}
	return nil
}

func (m *Puzzle) GetPortal() []*Portal {
	if m != nil {
		return m.Portal
	}
	return nil
}

func (m *Puzzle) GetSphere() []*Sphere {
	if m != nil {
		return m.Sphere
	}
	return nil
}

func (m *Puzzle) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Puzzle) GetTarget() uint32 {
	if m != nil {
		return m.Target
	}
	return 0
}

type Move struct {
	Timestamp            uint64    `protobuf:"fixed64,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Key                  string    `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                *Location `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Move) Reset()         { *m = Move{} }
func (m *Move) String() string { return proto.CompactTextString(m) }
func (*Move) ProtoMessage()    {}
func (*Move) Descriptor() ([]byte, []int) {
	return fileDescriptor_530ac3ae2cb4c87b, []int{8}
}

func (m *Move) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Move.Unmarshal(m, b)
}
func (m *Move) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Move.Marshal(b, m, deterministic)
}
func (m *Move) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Move.Merge(m, src)
}
func (m *Move) XXX_Size() int {
	return xxx_messageInfo_Move.Size(m)
}
func (m *Move) XXX_DiscardUnknown() {
	xxx_messageInfo_Move.DiscardUnknown(m)
}

var xxx_messageInfo_Move proto.InternalMessageInfo

func (m *Move) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Move) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Move) GetValue() *Location {
	if m != nil {
		return m.Value
	}
	return nil
}

type Solution struct {
	Timestamp            uint64   `protobuf:"fixed64,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Move                 []*Move  `protobuf:"bytes,2,rep,name=move,proto3" json:"move,omitempty"`
	Score                uint32   `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Solution) Reset()         { *m = Solution{} }
func (m *Solution) String() string { return proto.CompactTextString(m) }
func (*Solution) ProtoMessage()    {}
func (*Solution) Descriptor() ([]byte, []int) {
	return fileDescriptor_530ac3ae2cb4c87b, []int{9}
}

func (m *Solution) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Solution.Unmarshal(m, b)
}
func (m *Solution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Solution.Marshal(b, m, deterministic)
}
func (m *Solution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Solution.Merge(m, src)
}
func (m *Solution) XXX_Size() int {
	return xxx_messageInfo_Solution.Size(m)
}
func (m *Solution) XXX_DiscardUnknown() {
	xxx_messageInfo_Solution.DiscardUnknown(m)
}

var xxx_messageInfo_Solution proto.InternalMessageInfo

func (m *Solution) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Solution) GetMove() []*Move {
	if m != nil {
		return m.Move
	}
	return nil
}

func (m *Solution) GetScore() uint32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func init() {
	proto.RegisterType((*World)(nil), "perspective.World")
	proto.RegisterMapType((map[string]*joygo.Shader)(nil), "perspective.World.ShaderEntry")
	proto.RegisterType((*Location)(nil), "perspective.Location")
	proto.RegisterType((*Outline)(nil), "perspective.Outline")
	proto.RegisterType((*Block)(nil), "perspective.Block")
	proto.RegisterType((*Goal)(nil), "perspective.Goal")
	proto.RegisterType((*Portal)(nil), "perspective.Portal")
	proto.RegisterType((*Sphere)(nil), "perspective.Sphere")
	proto.RegisterType((*Puzzle)(nil), "perspective.Puzzle")
	proto.RegisterType((*Move)(nil), "perspective.Move")
	proto.RegisterType((*Solution)(nil), "perspective.Solution")
}

func init() { proto.RegisterFile("perspective.proto", fileDescriptor_530ac3ae2cb4c87b) }

var fileDescriptor_530ac3ae2cb4c87b = []byte{
	// 624 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x95, 0xd1, 0x6b, 0xdb, 0x3e,
	0x10, 0xc7, 0xb1, 0x63, 0xbb, 0xe9, 0xf9, 0x57, 0x68, 0xf5, 0xeb, 0x86, 0x29, 0x65, 0x64, 0x86,
	0x42, 0x46, 0xc1, 0x65, 0x19, 0x1b, 0x63, 0x6f, 0x4b, 0xd9, 0xf6, 0xd2, 0xb1, 0xa0, 0x3e, 0x14,
	0xfa, 0x32, 0x14, 0x47, 0x4b, 0xbc, 0xd8, 0x91, 0x91, 0xe5, 0xb4, 0xc9, 0xfe, 0x96, 0xbd, 0xee,
	0x4f, 0xd8, 0xdf, 0x37, 0x74, 0x52, 0x1a, 0x9b, 0x75, 0x7d, 0xed, 0x9b, 0xee, 0xee, 0x73, 0x92,
	0xee, 0x6b, 0xdd, 0x19, 0x0e, 0x4a, 0x2e, 0xab, 0x92, 0xa7, 0x2a, 0x5b, 0xf2, 0xa4, 0x94, 0x42,
	0x09, 0x12, 0x36, 0x5c, 0x47, 0xbb, 0xdf, 0xc5, 0xca, 0xf8, 0xe3, 0xdf, 0x2e, 0xf8, 0x57, 0x42,
	0xe6, 0x13, 0x42, 0xc0, 0x5b, 0xb0, 0x82, 0x47, 0x4e, 0xcf, 0xe9, 0xef, 0x52, 0x5c, 0x6b, 0x5f,
	0x95, 0xad, 0x79, 0xe4, 0xf6, 0x9c, 0xfe, 0x1e, 0xc5, 0x35, 0x39, 0x85, 0x83, 0x31, 0x4b, 0xe7,
	0x53, 0x29, 0xea, 0xc5, 0xe4, 0x6b, 0x2a, 0x72, 0x51, 0xcb, 0xa8, 0x83, 0x49, 0xfb, 0xdb, 0xc0,
	0x39, 0xfa, 0x35, 0xfc, 0x4d, 0x48, 0xde, 0x86, 0x3d, 0x03, 0x6f, 0x03, 0x77, 0x70, 0x50, 0xd6,
	0xeb, 0x75, 0xce, 0x23, 0xbf, 0xd7, 0xe9, 0x87, 0x83, 0xff, 0x93, 0x66, 0x1d, 0x23, 0x0c, 0x51,
	0x8b, 0x90, 0x37, 0x10, 0x54, 0x33, 0x36, 0xe1, 0x32, 0x0a, 0x10, 0x7e, 0xd6, 0x82, 0xb1, 0xa4,
	0xe4, 0x12, 0x81, 0x0f, 0x0b, 0x25, 0x57, 0xd4, 0xd2, 0x47, 0x1f, 0x21, 0x6c, 0xb8, 0xc9, 0x3e,
	0x74, 0xe6, 0x7c, 0x65, 0x8b, 0xd6, 0x4b, 0xf2, 0x1c, 0xfc, 0x25, 0xcb, 0x6b, 0x53, 0x74, 0x38,
	0x08, 0x13, 0x2d, 0x96, 0x49, 0xa1, 0x26, 0xf2, 0xce, 0x7d, 0xeb, 0xc4, 0x43, 0xe8, 0x5e, 0x88,
	0x94, 0xa9, 0x4c, 0x2c, 0xc8, 0x7f, 0xe0, 0xdc, 0xe0, 0x16, 0x3e, 0x75, 0x6e, 0xb4, 0x75, 0x8b,
	0xc9, 0x3e, 0x75, 0x6e, 0xb5, 0xb5, 0x42, 0x79, 0x7c, 0xea, 0xac, 0xb4, 0xb5, 0xc6, 0xfa, 0x7d,
	0xea, 0xac, 0xe3, 0xd7, 0xb0, 0xf3, 0xa5, 0x56, 0x79, 0xb6, 0x40, 0xa5, 0x0b, 0x5e, 0xcd, 0x36,
	0xea, 0xeb, 0x35, 0x79, 0x0a, 0x81, 0x55, 0xcc, 0x45, 0xaf, 0xb5, 0xe2, 0x35, 0xf8, 0xc3, 0x5c,
	0xa4, 0xf3, 0x7f, 0x7d, 0x32, 0xdc, 0xc8, 0xbd, 0x77, 0xa3, 0x4e, 0x73, 0x23, 0xf2, 0x12, 0xba,
	0xb9, 0xad, 0x01, 0x2f, 0x15, 0x0e, 0x9e, 0xb4, 0x54, 0xdc, 0x14, 0x48, 0xef, 0xb0, 0x78, 0x05,
	0xde, 0x27, 0xc1, 0xf2, 0xc7, 0x38, 0xfa, 0x97, 0x03, 0xc1, 0x48, 0x48, 0xf5, 0x28, 0xa7, 0x93,
	0x17, 0xe0, 0xe5, 0xd9, 0x62, 0x1e, 0xf9, 0x0f, 0xe1, 0x88, 0xc4, 0x3f, 0x20, 0xb8, 0x2c, 0x67,
	0x5c, 0xf2, 0xc7, 0x50, 0xe9, 0xa7, 0x0b, 0x81, 0x69, 0x15, 0x92, 0xc0, 0x8e, 0x30, 0xcf, 0x0b,
	0x2f, 0x10, 0x0e, 0x0e, 0x5b, 0xc9, 0xf6, 0xe9, 0xd1, 0x0d, 0x44, 0xfa, 0xe0, 0x8f, 0xf5, 0xbb,
	0x8a, 0x3a, 0xd8, 0x51, 0xa4, 0x45, 0xe3, 0x8b, 0xa3, 0x06, 0x20, 0x27, 0xe0, 0x4d, 0x05, 0xcb,
	0x23, 0x0f, 0xc1, 0x83, 0x16, 0xa8, 0x9f, 0x07, 0xc5, 0x30, 0x36, 0x34, 0x7e, 0xb0, 0xfb, 0x1b,
	0x1a, 0x43, 0xd4, 0x22, 0x1a, 0xae, 0x50, 0x35, 0xdb, 0xd0, 0x6d, 0xd8, 0x08, 0x4a, 0x2d, 0x42,
	0x7a, 0x10, 0x4e, 0x78, 0x95, 0xca, 0xac, 0x44, 0x6d, 0x76, 0x50, 0xb5, 0xa6, 0x4b, 0x4b, 0xaa,
	0x98, 0x9c, 0x72, 0x15, 0x75, 0x71, 0x78, 0x59, 0x2b, 0x4e, 0xc1, 0xfb, 0x2c, 0x96, 0x9c, 0x1c,
	0xc3, 0xae, 0xca, 0x0a, 0x5e, 0x29, 0x56, 0x94, 0x28, 0x4f, 0x40, 0xb7, 0x8e, 0xcd, 0x58, 0x70,
	0xb7, 0x63, 0xe1, 0x74, 0x33, 0x16, 0x3a, 0x0f, 0x7d, 0x07, 0xc3, 0xc4, 0x1c, 0xba, 0x97, 0x22,
	0xaf, 0xf1, 0x22, 0x0f, 0x1f, 0x74, 0x02, 0x5e, 0x21, 0x96, 0x7a, 0xd8, 0xfc, 0xad, 0xa4, 0xbe,
	0x27, 0xc5, 0x30, 0x39, 0x04, 0xbf, 0x4a, 0x85, 0x34, 0xa7, 0xef, 0x51, 0x63, 0x0c, 0xaf, 0xe1,
	0x38, 0x15, 0x45, 0xc2, 0x72, 0xae, 0x66, 0x3c, 0x63, 0x37, 0x4c, 0xf2, 0xe6, 0x06, 0xc3, 0xfd,
	0xd1, 0xd6, 0x18, 0xe9, 0x71, 0x7f, 0xdd, 0x9f, 0x66, 0x6a, 0x56, 0x8f, 0x93, 0x54, 0x14, 0x67,
	0xef, 0x6d, 0xda, 0x15, 0x93, 0xfc, 0xe2, 0xe2, 0xfc, 0xac, 0x91, 0x39, 0x15, 0xe3, 0x00, 0xff,
	0x0f, 0xaf, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0xac, 0x4e, 0xe3, 0xe8, 0x4c, 0x06, 0x00, 0x00,
}
